curl -X GET "https://contentsafetyjolgukwed.cognitiveservices.azure.com//contentsafety/text/categories/survival-advice2?api-version=2024-09-15-preview" \
     -H "Ocp-Apim-Subscription-Key: 5fhDUPeIfBKFtzrQcuPLk6qyeSsv3M3Gt4wJBYe5ROnRrwJdTx9bJQQJ99ALACYeBjFXJ3w3AAAHACOG0cTk" \
     -H "Content-Type: application/json"