curl -X POST "https://contentsafetydd.cognitiveservices.azure.com/contentsafety/text:analyzeCustomCategory?api-version=2024-09-15-preview" \
    -H "Ocp-Apim-Subscription-Key: ***" \
    -H "Content-Type: application/json" \
    -d "{
          \"text\": \"fishing\",
          \"categoryName\": \"survival-advice2\", 
          \"version\": 1
       }"
    