curl -X GET "https://contentsafetydddddd.cognitiveservices.azure.com//contentsafety/text/categories/operations/bdb9294c-3d45-408d-a382-38bf58c808c2?api-version=2024-09-15-preview" \
     -H "Ocp-Apim-Subscription-Key: ********************" \
     -H "Content-Type: application/json"