curl -X GET "https://contentsafetyddd.cognitiveservices.azure.com//contentsafety/text/categories/survival-advice2?api-version=2024-09-15-preview" \
     -H "Ocp-Apim-Subscription-Key: ***REDACTED***" \
     -H "Content-Type: application/json"