curl -X POST "https://contentsafetyjolgukddd.cognitiveservices.azure.com/contentsafety/text/categories/survival-advice2:build?api-version=2024-09-15-preview&version=1" \
     -H "Ocp-Apim-Subscription-Key: ***REDACTED***" \
     -H "Content-Type: application/json"