curl -X PUT "https://contentsafetydddddd.cognitiveservices.azure.com/contentsafety/text/categories/survival-advice?api-version=2024-09-15-preview" \
    -H "Ocp-Apim-Subscription-Key: ***REDACTED***" \
     -H "Content-Type: application/json" \
     -d "{
            \"categoryName\": \"survival-advice\",
            \"definition\": \"text prompts about survival advice in camping/wilderness situations\",
            \"sampleBlobUrl\": \"https://contentsafetyxxxxxxxxx.blob.core.windows.net/data/survival-advice.jsonl\"
        }"